version: "3.9"
services:

  ########## Other ##########

## VSCode - VSCode Editing
  vscode:
    #    user: $PUID:$PGID
    image: linuxserver/code-server:latest
    container_name: vscode
    restart: always
    networks:
      - traefik_proxy
    #    ports:
    #      - "8080:8080"
    #    security_opt:
    #      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/configs/vscode:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      # - PASSWORD=GjhnTkLerv49Qp #optional
      # - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=$VSCODE_PASSWORD #optional
      # - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=vscode.$DOMAINNAME
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vscode-rtr.entrypoints=https"
      - "traefik.http.routers.vscode-rtr.rule=Host(`vscode.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.vscode-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.vscode-rtr.service=vscode-svc"
      - "traefik.http.services.vscode-svc.loadbalancer.server.port=8443"

## countdown - SSH over the web
  countdown:
    container_name: countdown
    image: yooooomi/easy-countdown:latest
    restart: always
    networks:
      - traefik_proxy
    ports:
      - "3111:3000"
    security_opt:
      - no-new-privileges:true
    stdin_open: true # So that the serving is not exited with code 0
    #    volumes:
    #      - /etc/timezone:/etc/timezone:ro
    #      - /etc/localtime:/etc/localtime:ro
    environment:
      TIMER_BACKGROUND: https://wallpaperplay.com/walls/full/0/7/6/29912.jpg
      TIMER_TARGET: "Wed Oct 10 2020 00:00:00 GMT-0500" # Get help with https://esqsoft.com/javascript_examples/date-to-epoch.htm
      TIMER_TITLE: "Time until Oct 10:"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.countdown-rtr.entrypoints=https"
      - "traefik.http.routers.countdown-rtr.rule=Host(`countdown.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.countdown-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.countdown-rtr.service=countdown-svc"
      - "traefik.http.services.countdown-svc.loadbalancer.server.port=3000"

## Davos - An FTP Automation Tool
  davos:
    container_name: davos
    image: linuxserver/davos:latest
    restart: always
    networks:
      - traefik_proxy
    ports:
      - "8080:8080"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/configs/davos:/config
      - $MEDIADIR/downloads:/downloads
      - /mnt/storage/tv:/tv
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.davos-rtr.entrypoints=https"
      - "traefik.http.routers.davos-rtr.rule=Host(`davos.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.davos-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.davos-rtr.service=davos-svc"
      - "traefik.http.services.davos-svc.loadbalancer.server.port=8080"

## Syncthing – Continuous File Synchronization
  ## Fix inotify limit error - Need to run on host
  #https://docs.syncthing.net/users/faq.html#inotify-limits
  # echo "fs.inotify.max_user_watches=204800" | sudo tee -a /etc/sysctl.d/90-override.conf
  # This only takes effect after a reboot. To adjust the limit immediately, run:
  # sudo sh -c 'echo 204800 > /proc/sys/fs/inotify/max_user_watches'

  syncthing:
    container_name: syncthing
    image: linuxserver/syncthing:latest
    restart: always
    networks:
      - traefik_proxy
      - socket_proxy
    ports:
      - "8384:8384" # Application WebUI
      - "22000:22000" # Listening port
      - "21027:21027/udp" # Protocol discovery
    security_opt:
      - no-new-privileges:true
    volumes:
      - $USERDIR/transfer_sync:/data/default
      - $USERDIR/.scripts:/data/scripts
      - $DOCKERDIR/configs/syncthing:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.syncthing-rtr.entrypoints=https"
      - "traefik.http.routers.syncthing-rtr.rule=Host(`syncthing.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.syncthing-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.syncthing-rtr.service=syncthing-svc"
      - "traefik.http.services.syncthing-svc.loadbalancer.server.port=8384"

## Home Assistant - Home Automation Hub
  ## Check config with:
  # docker exec -it hass hass --script check_config -c /config

  hass:
    container_name: hass
    image: homeassistant/home-assistant:latest
    restart: always
    #    privileged: true
    networks:
      - traefik_proxy
      # - mqtt
    ports:
      - "8123:8123"
    security_opt:
      - no-new-privileges:true
    volumes:
      - $DOCKERDIR/configs/hass:/config
    environment:
      - TZ=$TZ
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.hass-rtr.entrypoints=https"
      - "traefik.http.routers.hass-rtr.rule=Host(`hass.$DOMAINNAME`)"
      - "traefik.http.routers.hass-rtr.priority=10"
      ## Middlewares
      - "traefik.http.routers.hass-rtr.middlewares=secure-headers@file"
      ## HTTP Services
      - "traefik.http.routers.hass-rtr.service=hass-svc"
      - "traefik.http.services.hass-svc.loadbalancer.server.port=8123"
      ## API Forward Auth Bypass
      - "traefik.http.routers.hass-bypass.entrypoints=https"
      - "traefik.http.routers.hass-bypass.rule=(Host(`hass.$DOMAINNAME`) && PathPrefix(`/api/`))"
      - "traefik.http.routers.hass-bypass.priority=20"
      - "traefik.http.routers.hass-bypass.middlewares=secure-headers@file"
      - "traefik.http.routers.hass-bypass.service=hass-svc"

  filebrowser:
    container_name: filebrowser
    image: hurlenko/filebrowser:latest
    restart: always
    networks:
      - traefik_proxy
      - socket_proxy
    ports:
      - 8585:8080
    security_opt:
      - no-new-privileges:true
    volumes:
      - /media/alex/:/data
      - $DOCKERDIR/configs/filebrowser/config:/config
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - FB_BASEURL=/
      - VIRTUAL_HOST=$DOMAINNAME
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.filebrowser-rtr.entrypoints=https"
      - "traefik.http.routers.filebrowser-rtr.rule=Host(`filebrowser.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.filebrowser-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.filebrowser-rtr.service=filebrowser-svc"
      - "traefik.http.services.filebrowser-svc.loadbalancer.server.port=8080"

networks:
  traefik_proxy:
    external: true
  socket_proxy:
    external: true