version: "3.9"
services:
########## Network Stack ##########

## Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy:latest
    restart: always
    privileged: true
    networks:
      - socket_proxy
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=1 # Needed for Ouroboros
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 #
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1 #
      - NODES=0
      - PLUGINS=0
      - SERVICES=1 #
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1 #
      - VOLUMES=1

networks:
  socket_proxy:
    external: true